version: '3.8'

services:
  api:
    build: .
    container_name: saas-api
    command: python main.py
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ../.env
    depends_on:
      - celery-worker
      - celery-beat

  celery-worker:
    build: .
    container_name: saas-celery-worker
    command: celery -A app.celery_worker worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ../.env
    depends_on:
      - redis

  celery-beat:
    build: .
    container_name: saas-celery-beat
    command: celery -A app.celery_worker beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ../.env
    depends_on:
      - redis
      - celery-worker

  redis:
    image: redis:alpine
    container_name: saas-redis
    ports:
      - "6380:6379" 