import json

def get_blog_content_prompt(keyword, language, blog_plan, video_info, category_names, section_chunks):
    if category_names:
        category_selection_instruction = f'''
CRITICAL INSTRUCTION - YOU MUST FOLLOW THIS EXACTLY:
You are writing content about "{keyword}".
AVAILABLE CATEGORIES (YOU MUST CHOOSE ONE OF THESE EXACT NAMES):
{chr(10).join(f"- {cat}" for cat in category_names)}
BEFORE writing any content, you MUST select the most appropriate category from the list above.
YOUR RESPONSE MUST START WITH THIS EXACT LINE:
SELECTED_CATEGORY: [EXACT category name from the list above]
IMPORTANT RULES:
- You can ONLY use categories from the list above
- You CANNOT create new category names
- You CANNOT use variations or synonyms
- You MUST use the EXACT category name as shown above
- If none seem perfect, choose the closest one
DO NOT write any content until you have selected a category.
DO NOT skip the category selection.
After the SELECTED_CATEGORY line, then write your full content.
EXAMPLE FORMAT:
SELECTED_CATEGORY: SCI-TECH
<article>
[Your full content here]
</article>
'''
    else:
        category_selection_instruction = ""

    video_section = ""
    if video_info:
        video_section = f'''
VIDEO INFORMATION:
Title: {video_info['title']}
URL: {video_info['url']}
Please include this video in the content with proper HTML embedding using the following format:
<div class="video-container" style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; margin: 20px 0;">
    <iframe src="{video_info['url'].replace('watch?v=', 'embed/')}" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<p class="video-caption" style="text-align: center; font-style: italic; margin-top: 10px;">{video_info['title']}</p>
IMPORTANT: Do not create any image tags or references to images that don't exist. Only use the images that will be generated by the system.
'''

    prompt = f'''{category_selection_instruction}
Create a comprehensive blog post about {keyword} in {language}.
BLOG PLAN:
{json.dumps(blog_plan, indent=2)}
{video_section}
REQUIREMENTS:
- Follow the exact headings and structure provided
- Use the source material as reference but rewrite in your own words
- Include proper HTML formatting
- Add relevant quotes and citations from sources
- Target word count: 1500-2000 words
- Use the exact title provided in the blog plan
- DO NOT include any h1 tags in the content (title is separate)
- Include anchor tags to sources contextually within the content, using a natural phrase such as: 'We can understand the situation better from the words of <a href="[URL]" target="_blank">[valuable anchor]</a>'. Anchor Tag must be part of the narrative, not a separate source list. And do not repeat links in anchor tags
STRUCTURED CONTENT REQUIREMENTS:
1. For biographies/people: ...
2. For topics/events: ...
3. For products/technology: ...
4. For all content types: ...
SOURCE MATERIAL BY SECTION:
{json.dumps(section_chunks, indent=2)}
Return the complete blog post with proper HTML formatting, including all tables and bullet points as specified above.'''
    return prompt 